### ISSUE TITLE
Unclear error if key env vars aren't set: type Nothing has no field renew

### ISSUE THREAD

**Issue by IanButterworth** [JuliaCloud/AWS.jl#284]
If neither `AWS_ACCESS_KEY_ID` nor `AWS_SECRET_ACCESS_KEY` are set, the lack of auth credentials isn't caught gracefully when trying `AWSConfig`

It also takes ~20 seconds before erroring.
When the keys are set it returns promptly.

```julia
julia> using AWS

julia> AWS.AWSConfig(region = "us-east-2")
ERROR: type Nothing has no field renew
Stacktrace:
 [1] setproperty!(x::Nothing, f::Symbol, v::Function)
   @ Base ./Base.jl:34
 [2] AWSCredentials(; profile::Nothing)
   @ AWS ~/.julia/packages/AWS/4QyI4/src/AWSCredentials.jl:167
 [3] top-level scope
   @ REPL[8]:1
```

AWS.jl v1.25.1
Julia v1.5 and v1.7

**Comment by mattBrzezinski** [comment]
`AWSConfig()` checks a few places in an attempt to create credentials. It follows the [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials) list for the most part:

https://github.com/JuliaCloud/AWS.jl/blob/master/src/AWSCredentials.jl#L151-L158

The reason you're seeing the ~20 second delay before the error is thrown is because it is trying to check various AWS endpoints for ECS/EC2 which can only be hit from AWS machines. Lowering the timeout on the request is a possibility however there will be a reasonable delay before falling over.

**Comment by IanButterworth** [comment]
That sounds fair. I think the main point is just that the error is rather opaque.

Perhaps it could say something like 
```
No viable auth credentials found, try setting credentials in accordance with https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials
```

**Comment by mattBrzezinski** [comment]
Definitely! Erroring handling in general can be improved for this package.
I can make the changes for this later tonight!

**Comment by IanButterworth** [comment]
Great, thanks!
