### ISSUE TITLE
Re-think how to run integration tests post-Invenia

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWS.jl#603]
I think it's hardly a secret now, but this is something that needs to be considered for the long-term maintenance of this package since that AWS account will no longer be available.

**Comment by Octogonapus** [comment]
I'd guess this is also the reason the CI tests on https://github.com/invenia/CloudWatchLogs.jl/pull/49 are failing.

I have had a great experience using [LocalStack](https://localstack.cloud/) to test an internal service which uses S3 and SQS. I'm sure some of AWS.jl's tests and other projects (e.g. CloudWatchLogs.jl) could be tested via the community version of LocalStack.

**Comment by mattBrzezinski** [comment]
Yeah I had met up w/ some folks at Invenia in charge of these and requested that they try and keep it alive as long as possible, I guess it's now gone. 

I did reach out to JuliaComputing and there are talks about porting this CI over into one of those accounts. I'll follow up with that now!

In the future, yeah I think LocalStack would be really good and running integrations w/o an AWS account would be amazing!

**Comment by ericphanson** [comment]
I think it's good to test against real-s3, since other services don't always replicate everything ("bug-for-bug"). E.g. when we tried Minio for s3 tests there are some subtle differences on the margin, like around versioning IIRC.

**Comment by mattBrzezinski** [comment]
> I don't believe that's why, and it hasn't been disabled.

I had tested yesterday and `AWS.jl` CI is working still so that account is still up! Forgot to follow up here with that.

**Comment by iamed2** [comment]
> I think it's good to test against real-s3, since other services don't always replicate everything ("bug-for-bug"). E.g. when we tried Minio for s3 tests there are some subtle differences on the margin, like around versioning IIRC.

I agree. Service support is often lacking and API changes can lag for months to years. I think the strategy used by the AWS packages right now is reasonable:
* Have an AWS account with trusted admins. Have those admins create a user that the CI can use, with limited and bounded permissions.
* Have the trusted admins store the user's access keys in GitHub secrets. Use Bors in order to let maintainers (can be a slightly wider set of people than admins) approve CI runs for PRs to run in the private context with access to those secrets. Ensure maintainers review PRs to make sure no untoward activity is occurring and no secrets are exposed before running CI. 
* Create a stack template, stored in the project repo for reference, with resources and a role to access those resources. Have the trusted admins deploy this stack, and store a reference to the stack/account in code (so they're versioned with the template). When updates are made to the stack, deploy with a new stack name so that CI can run on the candidate version and on the previous version. Old stacks can be deleted from time to time. 
* Provide instructions (e.g. this for [CloudWatchLogs.jl](https://invenia.github.io/CloudWatchLogs.jl/stable/pages/setup/)) so that untrusted users with access to AWS can run their own tests, including to propose changes to the stack. 
* Ensure maintainers review PRs and trusted admins monitor the AWS account to make sure the AWS costs remain low (e.g. the Public Continuous Integration account incurred $35/mo total costs which seems reasonable to me, although this could probably have been lowered further).

**Comment by c42f** [comment]
> I think it's good to test against real-s3

I'm not working with this code right now. But for what it's worth, I agree 100%.

Even S3 (basically the oldest and one of the most reliable of AWS services) can have weird semi-undocumented edge cases and it's important to test against those. For lesser used services there might not be a good emulation anywhere.

**Comment by omus** [comment]
@mattBrzezinski reached out to JuliaComputing who set us up with a separate AWS account for testing AWS.jl and other JuliaCloud packages such as AWSS3.jl. Maintainers with access to this account include @iamed2, @ericphanson, @mattBrzezinski, and myself.

@mattBrzezinski also deployed the CFN stack to the new account and updated the GHA secrets so that CI used the new account.
